version: '3.7'

services:
  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    command: "--replSet opensilex"
    
  rdf4j:
    image: eclipse/rdf4j-workbench:amd64-3.4.4
    ports:
       - 8080:8080
  
  opensilex-phis:
    build: .
    env_file: opensilex-phis.env
    ports:
       - 8081:8081
    
    command: "./bin/1.0.0-rc/opensilex.sh system install"
    
  nginx:
    image: nginx:1.17
    env_file: opensilex-phis.env
    volumes:
       - ./nginx.conf:/tmp/nginx.conf
       - ./output/nginx/log:/var/log/nginx
    ports:
       - "80:80"
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
