version: '3.7'

services:
  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    command: >
          bash -c "
          (
            sleep 3 &&
            mongo --eval \"rs.initiate({'_id':'opensilex','members':[{'_id':0,'host':'mongo:27017'}]})\" &&
            wait 
          ) & docker-entrypoint.sh --replSet opensilex
          "
  
  rdf4j:
    image: eclipse/rdf4j-workbench:amd64-3.4.4
    ports:
       - 8080:8080
  
  opensilex-phis:
    build: .
    env_file: opensilex-phis.env
    ports:
       - 8081:8081
    volumes:
      - ./config:/home/opensilex/config
      - ./logs:/home/opensilex/logs
      - ./data:/home/opensilex/data
    command: >
          bash -c "
            ./bin/opensilex.sh system install && 
            ./bin/opensilex.sh server start --host=192.168.1.94 --port=8081 --adminPort=4081
          "
    
  nginx:
    image: nginx:1.17
    env_file: opensilex-phis.env
    volumes:
       - ./nginx.conf:/tmp/nginx.conf
       - ./output/nginx/log:/var/log/nginx
    ports:
       - "80:80"
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
